### ISSUE TITLE
When launching on device, the app just closes.  Using Epic 5.3.2

### ISSUE THREAD

**Issue by OptimisticMonkey** [oculus-samples/Unreal-Phanto#1]
Trying to launch sample on device and it just exits.

**Comment by lilin40933** [comment]
same issue for me.

**Comment by jasonmeisel** [comment]
Thanks for the report! This issue should be fixed with the latest version. If you run into any other issues, please let us know!

**Comment by praful0203** [comment]
@jasonmeisel The app is still crashing when I try to launch it. I tried this with the latest code.
